igt/drv_module_reload: Check more carefully for a live driver
As drm_open_any() now quietly fails if there is no driver, this
nullifies the effectiviness of using gem_exec_nop as the test for a good
reload. Combine with gem_alive (and guarantee that gem_alive can detect
a dead driver, putting lie to

commit 032f30cb38bb03562ee7fde19cd278b1d8ac31a9
Author: Thomas Wood <thomas.wood@intel.com>
Date:   Tue Jan 13 13:33:57 2015 +0000

    lib: remove unnecessary checks on the drm_open_any return value

) first.

Bugzilla: https://bugs.freedesktop.org/show_bug.cgi?id=88573
Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>

diff --git a/tests/drv_module_reload b/tests/drv_module_reload
--- a/tests/drv_module_reload
+++ b/tests/drv_module_reload
@@ -43,7 +43,18 @@ echo 1 > /sys/class/vtconsole/vtcon1/bind
 
 modprobe snd_hda_intel
 
-# try to run something
-$SOURCE_DIR/gem_exec_nop > /dev/null && echo "module successfully loaded again"
+# does the device exist?
+if $SOURCE_DIR/gem_alive > /dev/null ; then
+	echo "module successfully loaded again"
+else
+	echo "failed to reload module successfully"
+	exit 2
+fi
+
+# then try to run something
+if ! $SOURCE_DIR/gem_exec_nop > /dev/null ; then
+	echo "failed to execute a simple batch after reload"
+	exit 3
+fi
 
 exit 0
